== Bereinigung der Benutzerkonten

Am 2020-12-06 15:01:53 wurden offenbar automatisch Benutzerkonten geändert / migriert oder ähnliche Aktionen. D.h. dieses Änderungsdatum sagt nichts über eine eventuelle Aktivität aus.

=== Löschung nicht aktivierter Benutzerkonten

Log absteigend im Datum

[cols="1,1"] 
|===
| *Datum*
| *Aktion*

| 10.07.2024
| Alle nicht aktivierten Benutzerkontoen bis gestern einzeln gelöscht, damit an diese keine Mails versendet werden.

| 31.07.2024
| Alle Benutzerkonten per sqlscript aktualisiert, bei denen aus mk_wettbewerb.EVENTS mit LoesungszettelCreated geschlossen wurde, dass 2024 ein Login erfolgt war.

| 04.08.2024
| DATE_MODIFIED bei allen Usern geändert, bei denen in authbv.EVENTS ein UserLoggedIn gefunden wurde. Teilweise Vergleich mit Teilnahmen 2024. Also 100% sicher bin ich mir nicht, aber viele mit 06.12.2020 konnten daraufhin nach hinten datiert werden
|===


=== Mailtextideen

UserLoggedIn-Events, noch seit Mitte 2023 vorlagen, wurden alle Benutzerkonten mit den URLs einmal aktualisiert.

Jetzt sind noch 3049 Benutzerkonten mit Jahr mod = 2020 vorhanden, für die kein LogIn Event gefunden wurde. Die Wahrscheinlichkeit für inaktive User ist groß.

Daher als Mailtext Hinweis auf Inaktivität seit Mitte 2020. Hinweis darauf, dass Konto am 1.1.2025 ohne weitere Information gelöscht wird, wenn bis 31.12.2024 kein Login erfolgt.

Hinweis, dass später bei Bedarf ein neues Benutzerkonto angelegt werden kann.

Hinweis, dass ich von einigen gebeten wurde, sie aus dem Mailverteiler zu streichen. Das Benutzerkonto wurde dabei nicht gelöscht. Deswegen noch einmal diese Mail.



=== Event-Log in der Auth-Database ist umfangreicher als das in der Minikänguru-Datenbank




[script,cmd]
----

MariaDB [authbv]> select * from EVENTS where name = 'UserLoggedIn' and year(time_occured) < 2024;

# 2020
+------+---------------------+--------------+---------------------+-------------------------------------------------+---------+
| ID   | DATE_MODIFIED       | NAME         | TIME_OCCURED        | BODY                                            | VERSION |
+------+---------------------+--------------+---------------------+-------------------------------------------------+---------+
+------+---------------------+--------------+---------------------+-------------------------------------------------+---------+

# 2021
+------+---------------------+--------------+---------------------+-------------------------------------------------+---------+
| ID   | DATE_MODIFIED       | NAME         | TIME_OCCURED        | BODY                                            | VERSION |
+------+---------------------+--------------+---------------------+-------------------------------------------------+---------+
+------+---------------------+--------------+---------------------+-------------------------------------------------+---------+


+------+---------------------+--------------+---------------------+-------------------------------------------------+---------+
| ID   | DATE_MODIFIED       | NAME         | TIME_OCCURED        | BODY                                            | VERSION |
+------+---------------------+--------------+---------------------+-------------------------------------------------+---------+
+------+---------------------+--------------+---------------------+-------------------------------------------------+---------+

# 2023
+------+---------------------+--------------+---------------------+-------------------------------------------------+---------+
| ID   | DATE_MODIFIED       | NAME         | TIME_OCCURED        | BODY                                            | VERSION |
+------+---------------------+--------------+---------------------+-------------------------------------------------+---------+
+------+---------------------+--------------+---------------------+-------------------------------------------------+---------+

----

