== Alles neu mit Angular 18

=== Neuer Workspace mit default app auth-app

[source,cli]
----
npx nx create-nx-workspace@latest auth-app-profil-app-ws --preset angular
----


[source,cli]
----
 NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Integrated monorepo, or standalone project? · integrated
✔ Application name · auth-app
✔ Which bundler would you like to use? · esbuild
✔ Default stylesheet format · scss
✔ Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? · No
✔ Test runner to use for end to end (E2E) tests · playwright
✔ Which CI provider would you like to use? · skip
✔ Would you like remote caching to make your build faster? · skip
----

=== profil-app

[source,cli]
----
npx nx generate @nrwl/angular:application profil-app
----

=== npm-Pakete hinzugefügt

[source,cli]
----
npm i @angular/material material-icons @angular/cdk
npm i @ngrx/store @ngrx/router-store @ngrx/store-devtools ngrx-store-localstorage @ngrx/effects
npm i @ngrx/eslint-plugin -D
----

=== Sheriff einbinden

Kleines feines https://angular-camp.de/blog/strategic-design-mit-sheriff-und-standalone/[Tutorial]

Sheriff ist ein tool, das ungewünschte direkte dependencies und damit zyklische Abhänigkeiten verhindert.

[source,cli]
----
npm i @softarc/sheriff-core @softarc/eslint-plugin-sheriff -D
npx sheriff init
----

https://softarc-consulting.github.io/sheriff/docs/dependency-rules


=== Libraries messages/api und messages/ui

[source,cli]
----
npx nx g @nx/angular:library api --directory=messages --flat --simpleName --style=scss --prefix=auth --standalone --tags=domain:shared,type:api --no-interactive --dry-run
----

Das generiert gleich einen Haufen Müll wie z.B. eine Komponente, die ich dort gar nicht haben will. Alles gelöscht und nur die services, das model und den loading-interceptor von mja-ws kopiert + exportiert.

[source,cli]
----
npx nx g @nx/angular:library ui --directory=messages --flat --simpleName --style=scss --prefix=auth --standalone --tags=domain:shared,type:ui --no-interactive --dry-run
----

=== theme einbinden

[source,cli]
----
cd libs
mkdir styles
touch theme.scss
----

=== Locale konfigurieren in app.config.ts

[src,typescript,source-file="app.config.ts"]
----
import { MAT_DATE_LOCALE } from '@angular/material/core';

...
registerLocaleData(LOCALE_ID, 'de');

...

providers: [
    ...,
    {
      provide: MAT_DATE_LOCALE,
      useValue: 'de-DE',
    },
    { provide: LOCALE_ID, useValue: 'de-DE' },
]
----

=== config

Mit der neuen Version von nx wird erst einmal kein environment-Verzeichnis mehr generiert. Das kann man manuell tun:

[src,cli]
----
npx nx generate environments --project=auth-app
----

Soll einen Provider kapseln, der über environmemt initialisiert wird um environment nirgends anders extra importieren zu müssen.

[src,cli]
---- 
npx nx g @nx/angular:library config --directory=libs --flat --simpleName --style=scss --prefix=auth --standalone --tags=domain:shared,type:config --no-interactive --dry-run
----

Dann wieder den überflüssigen Schmodder löschen
