== Alles neu mit Angular 18

=== Neuer Workspace mit default app auth-app

[source,cli]
----
npx nx create-nx-workspace@latest auth-app-profil-app-ws --preset angular
----


[source,cli]
----
 NX   Let's create a new workspace [https://nx.dev/getting-started/intro]

✔ Integrated monorepo, or standalone project? · integrated
✔ Application name · auth-app
✔ Which bundler would you like to use? · esbuild
✔ Default stylesheet format · scss
✔ Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? · No
✔ Test runner to use for end to end (E2E) tests · playwright
✔ Which CI provider would you like to use? · skip
✔ Would you like remote caching to make your build faster? · skip
----

=== profil-app

[source,cli]
----
npx nx generate @nrwl/angular:application profil-app
----

=== npm-Pakete hinzugefügt

[source,cli]
----
npm i @angular/material material-icons @angular/cdk
npm i @ngrx/store @ngrx/router-store @ngrx/store-devtools ngrx-store-localstorage @ngrx/effects
npm i @ngrx/eslint-plugin -D
----

=== Sheriff einbinden (habe ich später wieder entfernt, da es für mehrere apps nicht so einfach zu konfigurieren ist)

Kleines feines https://angular-camp.de/blog/strategic-design-mit-sheriff-und-standalone/[Tutorial]

Sheriff ist ein tool, das ungewünschte direkte dependencies und damit zyklische Abhänigkeiten verhindert.

[source,cli]
----
npm i @softarc/sheriff-core @softarc/eslint-plugin-sheriff -D
npx sheriff init
----

https://softarc-consulting.github.io/sheriff/docs/dependency-rules

=== Tooling: ein eigenes library schematic

https://nx.dev/extending-nx/recipes/local-generators

Wenn man das angular:library- schematic verwendet, kann man nicht verhindern, dasss gleich immer eine Komponente generiert wird, die man bei einfachen Service-Libraries mühsam wieder löschen muss.

Ich benötige am häufigsten eine Library, die einen injectable service bereitstellt und eine data-library, die Files für ngrx generiert.


=== Libraries messages/api und messages/ui

[source,cli]
----
npx nx g @nx/angular:library api --directory=messages --flat --simpleName --style=scss --prefix=auth --standalone --tags=domain:shared,type:api --no-interactive --dry-run
----

Das generiert gleich einen Haufen Müll wie z.B. eine Komponente, die ich dort gar nicht haben will. Alles gelöscht und nur die services, das model und den loading-interceptor von mja-ws kopiert + exportiert.

[source,cli]
----
npx nx g @nx/angular:library ui --directory=messages --flat --simpleName --style=scss --prefix=auth --standalone --tags=domain:shared,type:ui --no-interactive --dry-run
----

=== theme einbinden

[source,cli]
----
cd libs
mkdir styles
touch theme.scss
----

=== Locale konfigurieren in app.config.ts

[src,typescript,source-file="app.config.ts"]
----
import { MAT_DATE_LOCALE } from '@angular/material/core';

...
registerLocaleData(LOCALE_ID, 'de');

...

providers: [
    ...,
    {
      provide: MAT_DATE_LOCALE,
      useValue: 'de-DE',
    },
    { provide: LOCALE_ID, useValue: 'de-DE' },
]
----

=== config

Mit der neuen Version von nx wird erst einmal kein environment-Verzeichnis mehr generiert. Das kann man manuell tun:

[src,cli]
----
npx nx generate environments --project=auth-app
----

Soll einen Provider kapseln, der über environmemt initialisiert wird um environment nirgends anders extra importieren zu müssen.

Da es Differenzen zwischen den env-Konfigurationen für auth-app und profil-app gibt, hat jede Anwendung ihre eigene XXXConfiguration-Klasse als provider eingebunden.

=== shared http-Zeug


[src,cli]
---- 
npx nx g @nx/angular:library http --directory=libs --flat --simpleName --style=scss --prefix=auth --standalone --tags=domain:shared,type:util --no-interactive --dry-run
----

Dann wieder den überflüssigen Schmodder löschen

=== shared utils-Zeug
[src,cli]
---- 
npx nx g @nx/angular:library common-utils --directory=libs --flat --simpleName --style=scss --prefix=auth --standalone --tags=shared,type:util --no-interactive --dry-run
----


=== shared components-Zeug

[src,cli]
---- 
npx nx g @nx/angular:library common-components --directory=libs --flat --simpleName --style=scss --prefix=auth --standalone --tags=shared,type:ui --no-interactive --dry-run
----



=== auth-app-spezifische Libraries

=== sessions

[src,cli]
---- 
npx nx g @nx/angular:library model --directory=apps/auth-app/src/app/auth --flat --simpleName --style=scss --prefix=auth --standalone --tags=domain:auth,type:model --no-interactive --dry-run

npx nx g @nx/angular:library api --directory=apps/auth-app/src/app/auth --flat --simpleName --style=scss --prefix=auth --standalone --tags=domain:auth,type:api --no-interactive --dry-run

npx nx g @nx/angular:library data --directory=apps/auth-app/src/app/auth --flat --simpleName --style=scss --prefix=auth --standalone --tags=domain:auth,type:data --no-interactive --dry-run
----

==== Passwort vergessen

Library mit api (für facade und model), data für service, feature für die Component

[src,cli]
---- 
npx nx g @nx/angular:library data --directory=apps/auth-app/src/app/forgot-password --flat --simpleName --style=scss --prefix=auth --standalone --tags=domain:auth,type:data --no-interactive --dry-run

npx nx g @nx/angular:library api --directory=apps/auth-app/src/app/forgot-password --flat --simpleName --style=scss --prefix=auth --standalone --tags=domain:auth,type:api --no-interactive --dry-run

npx nx g @nx/angular:library feature ---directory=apps/auth-app/src/app/forgot-password --flat --simpleName --style=scss --prefix=auth --standalone --tags=domain:auth,type:feature --no-interactive --dry-run
----

=== profil-app-spezifische Libraries

=== sessions

[src,cli]
---- 
npx nx g @nx/angular:library model --directory=apps/profil-app/src/app/auth --flat --simpleName --style=scss --prefix=auth --standalone --tags=domain:profil,type:model --no-interactive --dry-run

npx nx g @nx/angular:library api --directory=apps/profil-app/src/app/auth --flat --simpleName --style=scss --prefix=auth --standalone --tags=domain:profil,type:api --no-interactive --dry-run

npx nx g @nx/angular:library data --directory=apps/profil-app/src/app/auth --flat --simpleName --style=scss --prefix=auth --standalone --tags=domain:profil,type:data --no-interactive --dry-run
----

