<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>de.egladil.web</groupId>
	<artifactId>auth-validations</artifactId>
	<version>1.0.0</version>
	<packaging>jar</packaging>

	<name>auth-validations</name>
	<description>annotations, validators, patterns for auth</description>


	<properties>
		<hibernate-validator.version>9.0.1.Final</hibernate-validator.version>
		<commons-lang3.version>3.18.0</commons-lang3.version>
		<slf4j.version>2.0.16</slf4j.version>
		<slf4j.version>1.7.33</slf4j.version>
		<logback.version>1.5.25</logback.version>
		<junit.version>5.8.2</junit.version>
		<mockito.version>5.18.0</mockito.version>

		<mixin-maven-plugin.version>1.0.6</mixin-maven-plugin.version>
		<egladil-maven-mixins.version>1.0.1</egladil-maven-mixins.version>

		<!-- Start mixin-properties -->
		<maven.compiler.release>21</maven.compiler.release>
		<pmd.failOnViolation>true</pmd.failOnViolation>
		<spotbugs.failOnError>true</spotbugs.failOnError>
		<jacoco.exclusion-1>**/*Dto*.class</jacoco.exclusion-1>
		<jacoco.exclusion-2>**/*Application*.class</jacoco.exclusion-2>
		<jacoco.exclusion-3>**/ResponseStatus.class</jacoco.exclusion-3>
		<jacoco.exclusion-4>**/healthchecks/**</jacoco.exclusion-4>

		<java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
		<maven.compiler.parameters>true</maven.compiler.parameters>
	</properties>

	<dependencies>
		<dependency>
			<groupId>org.hibernate.validator</groupId>
			<artifactId>hibernate-validator</artifactId>
			<version>${hibernate-validator.version}</version>
		</dependency>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>${slf4j.version}</version>
		</dependency>

		<dependency>
			<groupId>org.apache.commons</groupId>
			<artifactId>commons-lang3</artifactId>
			<version>${commons-lang3.version}</version>
		</dependency>

		<!-- Test START -->
		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<version>${junit.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-core</artifactId>
			<version>${mockito.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.mockito</groupId>
			<artifactId>mockito-junit-jupiter</artifactId>
			<version>${mockito.version}</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
			<version>2.16.1</version>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>org.glassfish</groupId>
			<artifactId>jakarta.el</artifactId>
			<version>5.0.0-M1</version>
			<scope>test</scope>
		</dependency>


		<!-- Logback Classic -->
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-classic</artifactId>
			<version>${logback.version}</version>
			<scope>test</scope>
		</dependency>

		<!-- Logback Core (required by Logback Classic) -->
		<dependency>
			<groupId>ch.qos.logback</groupId>
			<artifactId>logback-core</artifactId>
			<version>${logback.version}</version>
			<scope>test</scope>
		</dependency>
		<!-- Logging ENDE -->

		<!-- Test ENDE -->

	</dependencies>

	<build>

		<finalName>${project.artifactId}</finalName>

		<plugins>
			<plugin>
				<groupId>com.playtika.maven.plugins</groupId>
				<artifactId>mixin-maven-plugin</artifactId>
				<version>${mixin-maven-plugin.version}</version>
				<extensions>true</extensions>
				<configuration>
					<mixins>
						<mixin>
							<groupId>de.egladil</groupId>
							<artifactId>java-core-mixin</artifactId>
							<version>${egladil-maven-mixins.version}</version>
						</mixin>
						<mixin>
							<groupId>de.egladil</groupId>
							<artifactId>java-linting-mixin</artifactId>
							<version>${egladil-maven-mixins.version}</version>
						</mixin>
						<mixin>
							<groupId>de.egladil</groupId>
							<artifactId>java-code-quality-mixin</artifactId>
							<version>${egladil-maven-mixins.version}</version>
						</mixin>
						<mixin>
							<groupId>de.egladil</groupId>
							<artifactId>java-unittest-mixin</artifactId>
							<version>${egladil-maven-mixins.version}</version>
						</mixin>
						<mixin>
							<groupId>de.egladil</groupId>
							<artifactId>java-unittestcoverage-mixin</artifactId>
							<version>${egladil-maven-mixins.version}</version>
						</mixin>
						<mixin>
							<groupId>de.egladil</groupId>
							<artifactId>java-pitest-mixin</artifactId>
							<version>${egladil-maven-mixins.version}</version>
						</mixin>
						<mixin>
							<groupId>de.egladil</groupId>
							<artifactId>java-security-mixin</artifactId>
							<version>${egladil-maven-mixins.version}</version>
						</mixin>
					</mixins>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
