<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>


	<groupId>de.egladil.web</groupId>
	<artifactId>authprovider</artifactId>
	<version>9.2.0</version>
	<packaging>jar</packaging>

	<name>authprovider</name>
	<url>https://github.com/heike2718/authprovider.git</url>
	<description>Authenticationprovider für Mathe-Jung-Alt</description>

	<properties>
		<auth-validations.version>1.0.0</auth-validations.version>
		<quarkus.platform.artifact-id>quarkus-bom</quarkus.platform.artifact-id>
		<quarkus.platform.group-id>io.quarkus.platform</quarkus.platform.group-id>
		<quarkus.platform.version>3.30.6</quarkus.platform.version>
		<apache.shiro.version>2.1.0</apache.shiro.version>
		<java-jwt.version>4.5.0</java-jwt.version>

		<mixin-maven-plugin.version>1.0.6</mixin-maven-plugin.version>
		<egladil-maven-mixins.version>1.0.1</egladil-maven-mixins.version>

		<!-- Start mixin-properties -->
		<maven.compiler.release>21</maven.compiler.release>
		<pmd.failOnViolation>true</pmd.failOnViolation>
		<spotbugs.failOnError>true</spotbugs.failOnError>
		<jacoco.exclusion-1>**/*Dto*.class</jacoco.exclusion-1>
		<jacoco.exclusion-2>**/*Application*.class</jacoco.exclusion-2>
		<jacoco.exclusion-3>**/ResponseStatus.class</jacoco.exclusion-3>
		<jacoco.exclusion-4>**/healthchecks/**</jacoco.exclusion-4>

		<java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
		<maven.compiler.parameters>true</maven.compiler.parameters>
		<!-- Ende mixin-propetries -->
	</properties>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>${quarkus.platform.group-id}</groupId>
				<artifactId>${quarkus.platform.artifact-id}</artifactId>
				<version>${quarkus.platform.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>

		<dependency>
			<groupId>de.egladil.web</groupId>
			<artifactId>auth-validations</artifactId>
			<version>${auth-validations.version}</version>
		</dependency>

		<dependency>
			<groupId>com.auth0</groupId>
			<artifactId>java-jwt</artifactId>
			<version>${java-jwt.version}</version>
			<exclusions>
				<exclusion>
					<groupId>com.fasterxml.jackson.core</groupId>
					<artifactId>jackson-databind</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.apache.shiro</groupId>
			<artifactId>shiro-core</artifactId>
			<version>${apache.shiro.version}</version>
			<exclusions>
				<exclusion>
					<groupId>org.apache.shiro.crypto</groupId>
					<artifactId>shiro-hashes-bcrypt</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<!-- Quarkus START -->
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-agroal</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-reactive-routes</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-rest-client</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-rest-client-jackson</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-rest</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-rest-jackson</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-hibernate-validator</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-mailer</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-hibernate-orm</artifactId>
		</dependency>


		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-smallrye-fault-tolerance</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-smallrye-context-propagation</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-smallrye-jwt</artifactId>
		</dependency>
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-smallrye-openapi</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-arc</artifactId>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-jdbc-mariadb</artifactId>
		</dependency>

		<!-- Quarkus END -->
		<dependency>
			<groupId>commons-io</groupId>
			<artifactId>commons-io</artifactId>
		</dependency>

		<!-- Test START -->
		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-junit5</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>io.rest-assured</groupId>
			<artifactId>rest-assured</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-junit5-mockito</artifactId>
			<scope>test</scope>
		</dependency>

		<dependency>
			<groupId>io.quarkus</groupId>
			<artifactId>quarkus-jacoco</artifactId>
			<scope>test</scope>
		</dependency>

		<!-- Test ENDE -->
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>${quarkus.platform.group-id}</groupId>
				<artifactId>quarkus-maven-plugin</artifactId>
				<version>${quarkus.platform.version}</version>
				<extensions>true</extensions>
				<executions>
					<execution>
						<goals>
							<goal>build</goal>
							<goal>generate-code</goal>
							<goal>generate-code-tests</goal>
						</goals>
					</execution>
				</executions>
			</plugin>

			<plugin>
				<groupId>com.playtika.maven.plugins</groupId>
				<artifactId>mixin-maven-plugin</artifactId>
				<version>${mixin-maven-plugin.version}</version>
				<extensions>true</extensions>
				<configuration>
					<mixins>
						<mixin>
							<groupId>de.egladil</groupId>
							<artifactId>java-core-mixin</artifactId>
							<version>${egladil-maven-mixins.version}</version>
						</mixin>
						<mixin>
							<groupId>de.egladil</groupId>
							<artifactId>java-linting-mixin</artifactId>
							<version>${egladil-maven-mixins.version}</version>
						</mixin>
						<mixin>
							<groupId>de.egladil</groupId>
							<artifactId>java-code-quality-mixin</artifactId>
							<version>${egladil-maven-mixins.version}</version>
						</mixin>
						<mixin>
							<groupId>de.egladil</groupId>
							<artifactId>java-quarkustest-coverage-mixin</artifactId>
							<version>${egladil-maven-mixins.version}</version>
						</mixin>
						<mixin>
							<groupId>de.egladil</groupId>
							<artifactId>java-security-mixin</artifactId>
							<version>${egladil-maven-mixins.version}</version>
						</mixin>
					</mixins>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
