== Aufsetzen der Angular-Anwendung

Hier die Befehle zum Generieren von Dingen für das Frontend

[source,cli]
----
npx create-nx-workspace@18.3.5 bv-admin-app
----

Habe mich für ein *standalone* project entschieden, weil es mit integrated nicht geklappt hat.

Report der gewählten Optionen:

[source,cli]
---
✔ Which stack do you want to use? · angular
✔ Integrated monorepo, or standalone project? · standalone
✔ Which bundler would you like to use? · esbuild
✔ Default stylesheet format · scss
✔ Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? · No
✔ Test runner to use for end to end (E2E) tests · playwright
✔ Do you want Nx Cloud to make your CI fast? · skip

---

=== npm-Pakete hinzugefügt

[source,cli]
----
npm i @angular/material material-icons @angular/cdk
npm i @ngrx/store @ngrx/router-store @ngrx/store-devtools ngrx-store-localstorage @ngrx/effects
npm i @ngrx/eslint-plugin -D
----


=== scripts hinzugefügt

Beachte: NX_DAEMON=false war erforderlich, weil nach ein bisschen Herumkofigurieren im Workspace kein einziger nx- Befehl ohne die Fehlemeldung

"NX   Cannot read properties of null (reading 'message')"

mehr ausgeführt werden konnte. Gestört hatte das vor allem, beim verwenden on schematics. Aber später auch bei den anderen nx-Befehlen.

[source,json,source-file="package.json"]
----
...

  "scripts": {    
    "ng": "nx",
    "postinstall": "node ./decorate-angular-cli.js",
    "start": "NX_DAEMON=false nx serve",
    "build:local": "NX_DAEMON=false npx nx build bv-admin-app -c local --output-hashing=all --base-href /bv-admin-app/ --skip-nx-cache",
    "build:heikeqs": "NX_DAEMON=false npx nx build bv-admin-app -c heikeqs --output-hashing=all --base-href /bv-admin-app/ --skip-nx-cache",
    "build:prod": "NX_DAEMON=false npx nx run bv-admin-app:build:production --output-hashing=all --base-href /bv-admin-app/ --skip-nx-cache",
    "test": "NX_DAEMON=false npx nx test",
    "test:all": "NX_DAEMON=false npx nx run-many --target=test --all",
    "lint:all": "NX_DAEMON=false npx nx run-many --target=lint --all",
    "full-check": "NX_DAEMON=false npx nx run-s lint:all test:all build",
    "graph": "NX_DAEMON=false npx nx graph"
  },

...
----

=== buildprofile einrichten

Im root-Verzeichnis des workspaces einen Verzeichnisbaum

----
bv-admin-app
  |-- build-env
        |-- environment.heikeqs.ts
        |-- environment.local.ts
        |-- index.heikeqs.html
        |-- index.prod.html
  |-- src
      |-- app
      |-- assets
      |-- environments
  |-- project.json
----

Diese Files werden in project.json verwendet, um die dev-Files zu ersetzen.


=== selector prefix configuriert

Nach prefix suchen und dort app  durch das spezifischere prefix 'bv-admin' ergänzen.


=== Sheriff einbinden

Kleines feines https://angular-camp.de/blog/strategic-design-mit-sheriff-und-standalone/[Tutorial]

Sheriff ist ein tool, das ungewünschte direkte dependencies und damit zyklische Abhänigkeiten verhindert.

[source,cli]
----
npm i @softarc/sheriff-core @softarc/eslint-plugin-sheriff -D
----

Anschließend in .eslint.rc einbinden:

[source,json,source-file=".eslint.rc"]
----
{
  [...],
  "overrides": [
    [...]
    {
      "files": ["*.ts"],
      "extends": ["plugin:@softarc/sheriff/default"]
    }
  ]
}
----

Sheriff-Konfigurationsdatei sheriff.config.ts im root-Verzeichnis anlegen und mit der Kopie aus https://github.com/softarc-consulting/sheriff/tree/main[angular-iii] füllen.

=== Locale konfigurieren in app.config.ts

[src,typescript,source-file="app.config.ts"]
----
import { MAT_DATE_LOCALE } from '@angular/material/core';

...
registerLocaleData(LOCALE_ID, 'de');

...

providers: [
    ...,
    {
      provide: MAT_DATE_LOCALE,
      useValue: 'de-DE',
    },
    { provide: LOCALE_ID, useValue: 'de-DE' },
]
----


== Folders - Anwendungsstruktur

Ich werde mit einem Konzep aus dem Beispiel https://github.com/softarc-consulting/sheriff/tree/main[angular-iii] starten ohne nx-workspace-Zeug.
(Nachdem ich einen Tag vergeblich mit den Änderungen im tooling von nx gekämpft hatte, gebe ich auf)

Hier werden keine libs generiert, sondern alles nur durch Verzeichnisse strukturiert und über index.ts exportiert. Das scheint mir ein leichtgewichtiger Ansatz für ein neues Projekt zu sein.

Um relative Pfade in imports zu vermeiden, werden hierzu manuell Pfad-Mappings in tsconfig.json eingefügt.


== shell

In dem Beispiel von R.Hahnekamp ist shell sowas wie core - also Navigation und Services fürs error-handling

=== Material-Layout in die shell


[src,cli]
----
mkdir src/app/shell/layout -p
touch src/app/shell/layout/index.ts
----

Eintrag in tsconfig.json

[src,json,source-file="tsconfig.json"]
----
    "paths": {
      "@bv-admin-app/shell/layout": ["src/app/shell/layout/index.ts"]
    },
----


Statt

[src,css,source-file="themes.scss"]
----
$mja-primary: mat.define-palette($primary-palette, 700, 300, 900);
----

Muss es jetzt 

[src,css,source-file="themes.scss"]
----
$mja-primary: mat.m2-define-palette($primary-palette, 700, 300, 900);
----

heißen

Dann die styles in project.json eingebunden:


[src,json,source-file="project.json"]
----
...
        "assets": [
          {
            "glob": "**/*",
            "input": "apps/auth-admin-app/src/assets"
          }
        ],
         "styles": [
          "src/app/shell/layout/theme.scss",
          "src/styles.scss",
          "node_modules/material-icons/iconfont/material-icons.scss"
        ],
...
----


==== sidenav in die shell

[src,cli]
----
mkdir src/app/shell/layout/sidenav -p
----

Dann die component aus mkbiza-app kopiert und angepasst.

==== navbar in die shell

[src,cli]
----
mkdir src/app/shell/layout/navbar -p
----

Dann die component aus mkbiza-app kopiert und angepasst.

=== services

[src,cli]
----
mkdir src/app/shell/services -p
touch src/app/shell/services/error-handler.service.ts
----

Implementierung des ErrorHandlerService aus anderem Projekt kopiert und angepasst. Registrieren in app.confif.ts:

[src,typescript,source-file="app.config.ts"]
----
import { ErrorHandlerService } from '@bv-admin-app/shared/config';

...
  providers: [
    ...,    
    { provide: ErrorHandler, useClass: ErrorHandlerService },
  ]
----


== shared

Nach shared kommen Dinge, die von fachlichen "Modulen" verwendet werden. Also Zeug von übergreifendem Interesse.

=== config

Soll einen Provider kapseln, der über environmemt initialisiert wird um environment nirgends anders extra importieren zu müssen.

[src,cli]
----
mkdir src/app/shared/config -p
touch src/app/shared/config/configuration.ts
touch src/app/shared/config/index.ts
----

Eintrag in tsconfig.json

[src,json,source-file="tsconfig.json"]
----
    "paths": {
      "@bv-admin-app/shared/config": ["src/app/shared/config/index.ts"]
    },
----


Dann Configuration in app.config.ts zum Provider machen:

[src,typescript,source-file="app.config.ts"]
----
import { Configuration } from '@bv-admin-app/shared/config';

...
  providers: [
    ...,
    {
      provide: Configuration,
      useFactory: () =>
        new Configuration(
          environment.baseUrl,
          environment.assetsPath,
          'bv-admin-app',
          environment.production
        ),
    },
  ]
----

=== messages

Hier leben der Loading-Indocator und die Message-Komponente

[src,cli]
----
mkdir src/app/shared/messages/api -p
touch src/app/shared/messages/api/message.model.ts
touch src/app/shared/messages/api/message.service.ts
touch src/app/shared/messages/api/loading.interceptor.ts
touch src/app/shared/messages/api/loading.service.ts
touch src/app/shared/messages/api/silent-load.context.ts
touch src/app/shared/messages/api/index.ts

mkdir src/app/shared/messages/ui/loading-indicator -p
mkdir src/app/shared/messages/ui/message -p
touch src/app/shared/messages/ui/index.ts
touch src/app/shared/messages/ui/loading-indicator/loading-indicator.component.ts
touch src/app/shared/messages/ui/message/message.component.ts
----

*Eintrag in tsconfig.json*

[src,json,source-file="tsconfig.json"]
----
    "paths": {
      "@bv-admin-app/shared/messages/api": ["src/app/shared/messages/api/index.ts"],
      "@bv-admin-app/shared/messages/ui": ["src/app/shared/messages/ui/index.ts"]
    },
----

*LoadingInterceptor registrieren:*

[src,typescript,source-file="app.config.ts"]
----
import { LoadingInterceptor } from '@bv-admin-app/shared/messages/api';
...

providers: [
  ...
  { provide: HTTP_INTERCEPTORS, multi: true, useClass: LoadingInterceptor },
  ...
]

...
----

=== http

Hier hin kommen Interceptoren.

[src,cli]
----
mkdir src/app/shared/http -p
touch src/app/shared/http/auth-admin-api-http.interceptor.ts
touch src/app/shared/http/http.utils.ts
touch src/app/shared/http/error.interceptor.ts
touch src/app/shared/http/index.ts
----

Implementierung aus anderen Projekten übernommen. Anschließend die Interceptoren registrieren:

[src,typescript,source-file="app.config.ts"]
----
import { LoadingInterceptor } from '@bv-admin-app/shared/messages/api';
...

providers: [
  ...
  { provide: HTTP_INTERCEPTORS, multi: true, useClass: AuthAdminAPIHttpInterceptor },
  { provide: HTTP_INTERCEPTORS, multi: true, useClass: ErrorInterceptor },
  ...
]

...
----

=== auth

Das wird jetzt nicht mehr im Detail dokumentiert. Nur ein paar Stichworte:

Es gibt ein api, ein data und ein model, wobei von data einige Dinge exportiert werden, die nicht nur in api, sondern auch in local-storage-data verwendet werden.

Damit nicht alle actions public sind, werden nur die exporiert, die von der AuthFacade und von LocalStorageEffects benötigt werden.

=== local-storage-data

Dient zum Syncronisieren des Stors mit dem LocalStorage, damit man nach F5 seine Session noch hat, sonst muss man sich ständig neu einloggen.
Das alles wird in app.config.ts registriert




