== Aufsetzen der Angular-Anwendung

Hier die Befehle zum Generieren von Dingen für das Frontend

[source,cli]
----
npx create-nx-workspace@latest authadmin-ws
----

Habe mich für ein *integrated* project entschieden, weil ich es zuvor mit standalone nicht geschafft habe, die importe aufzulösen

Report der gewählten Optionen:

[source,cli]
---
✔ Which stack do you want to use? · angular
✔ Integrated monorepo, or standalone project? · integrated
✔ Application name · auth-admin-app
✔ Which bundler would you like to use? · esbuild
✔ Default stylesheet format · scss
✔ Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? · No
✔ Test runner to use for end to end (E2E) tests · playwright
✔ Do you want Nx Cloud to make your CI fast? · skip
---

=== npm-Pakete hinzugefügt

[source,cli]
----
npm i @ngrx/store @ngrx/router-store @ngrx/store-devtools ngrx-store-localstorage @ngrx/effects
npm i @ngrx/eslint-plugin -D
npm i @angular/material material-icons
npm i angular2-uuid
npm i ng2-charts
npm i @angular/cdk
----


=== scripts hinzugefügt

[source,json,source-file="package.json"]
----
  "scripts": {
    "ng": "nx",
    "postinstall": "node ./decorate-angular-cli.js",
    "start": "nx serve auth-admin-app",
    "build:local": "npx nx build auth-admin-app -c local --output-hashing=all --base-href /auth-admin-app/ --skip-nx-cache",
    "build:heikeqs": "npx nx build auth-admin-app -c heikeqs --output-hashing=all --base-href /auth-admin-app/ --skip-nx-cache",
    "build:prod": "npx nx run auth-admin-app:build:production --output-hashing=all --base-href /auth-admin-app/ --skip-nx-cache",
    "test": "npx nx test",
    "test:all": "npx nx run-many --target=test --all",
    "lint:all": "npx nx run-many --target=lint --all",
    "full-check": "npx nx run-s lint:all test:all build",
    "graph": "npx nx graph"
  },

----

=== buildprofile einrichten

Im root-Verzeichnis des workspaces einen Verzeichnisbaum

----
authadmin-ws
|-- apps
      |-- auth-admin-app
            |-- build-env
                  |-- environment.heikeqs.ts
                  |-- environment.local.ts
                  |-- index.heikeqs.html
                  |-- index.prod.html
            |-- src
            |-- project.json
|-- libs
----

Diese Files werden in project.json verwendet, um die dev-Files zu ersetzen.

Die Profile werden im project.json der app konfiguriert: 

----
authadmin-ws
|-- apps
     |-- auth-admin-app
     |-- project.json
----


=== selector prefix configuriert

Nach prefix suchen und dort app  durch das spezifischere prefix 'auth-admin' ergänzen.


=== Sheriff einbinden

Kleines feines https://angular-camp.de/blog/strategic-design-mit-sheriff-und-standalone/[Tutorial]

Sheriff ist ein tool, das ungewünschte direkte dependencies und damit zyklische Abhänigkeiten verhindert.

[source,cli]
----
npm i @softarc/sheriff-core @softarc/eslint-plugin-sheriff -D
----

Anschließend in .eslint.rc einbinden:

[source,json,source-file=".eslint.rc"]
----
{
  [...],
  "overrides": [
    [...]
    {
      "files": ["*.ts"],
      "extends": ["plugin:@softarc/sheriff/default"]
    }
  ]
}
----

Sheriff-Konfigurationsdatei sheriff.config.ts im root-Verzeichnis anlegen und mit der Kopie aus dem Tutorial füllen.

=== Locale konfigurieren in app.config.ts

[src,typescript,source-file="app.config.ts"]
----
import { MAT_DATE_LOCALE } from '@angular/material/core';

...
registerLocaleData(LOCALE_ID, 'de');

...

providers: [
    ...,
    {
      provide: MAT_DATE_LOCALE,
      useValue: 'de-DE',
    },
    { provide: LOCALE_ID, useValue: 'de-DE' },
]
----


== Libraries

=== Config-Lib

Soll einen Provider kapseln, der über environmemt initialisiert wird um environment nirgends anders extra importieren zu müssen.

[src,cli]
----
npx nx generate @nx/angular:library --name=config --directory=libs/shared/config --projectNameAndRootFormat=as-provided --skipModule=true --tags=domain:shared --no-interactive --dry-run
----

Dann Configuration in app.config.ts zum Provider machen:

[src,typescript,source-file="app.config.ts"]
----
...
  providers: [
    ...,
    {
      provide: Configuration,
      useFactory: () =>
        new Configuration(
          environment.baseUrl,
          environment.assetsPath,
          'mkbiza-app',
          environment.production
        ),
    },
  ]
----

=== Material-Layout in eine layout-Lib

[src,cli]
----
npx nx generate @nx/angular:library --name=layout --directory=libs/shared/layout --projectNameAndRootFormat=as-provided --style=scss --tags=domain:shared --no-interactive --dry-run 
----

Musste selector anpassen - war auf lib gesetzt

[src,html,source-file="layout.component.html"]
----
<ng-content></ng-content>
----

Aus git/minikaenguru/statistics/frontend/.../layout/src/lib das Verzeichnis scss kopiert und die styles in project.json eingebunden:


[src,json,source-file="project.json"]
----
...
        "assets": [
          {
            "glob": "**/*",
            "input": "apps/auth-admin-app/src/assets"
          }
        ],
        "styles": [
          "src/app/shared/layout/src/lib/scss/theme.scss",
          "src/styles.scss",
          "node_modules/material-icons/iconfont/material-icons.scss"
        ],
...
----


==== sidenav

[source,cli]
----
npx nx generate @nx/angular:component --name=sidenav --directory=apps/auth-admin-app/src/app/navigation/sidenav --nameAndDirectoryFormat=as-provided --style=scss --prefix=auth-admin --no-interactive --dry-run
----

==== header

[source,cli]
----
npx nx generate @nx/angular:component --name=header --directory=src/app/navigation/header --nameAndDirectoryFormat=as-provided --style=scss --no-interactive --dry-run
----

=== HomeComponent

[source,cli]
----
npx nx generate @nx/angular:component --name=home --directory=src/app/home --nameAndDirectoryFormat=as-provided --style=scss --no-interactive 
----


