== Aufsetzen der Angular-Anwendung

Hier die Befehle zum Generieren von Dingen für das Frontend

[source,cli]
----
npx create-nx-workspace@18.3.5 bv-admin-app
----

Habe mich für ein *standalone* project entschieden, weil es mit integrated nicht geklappt hat.

Report der gewählten Optionen:

[source,cli]
---
✔ Which stack do you want to use? · angular
✔ Integrated monorepo, or standalone project? · standalone
✔ Which bundler would you like to use? · esbuild
✔ Default stylesheet format · scss
✔ Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? · No
✔ Test runner to use for end to end (E2E) tests · playwright
✔ Do you want Nx Cloud to make your CI fast? · skip

---

=== npm-Pakete hinzugefügt

[source,cli]
----
npm i @angular/material material-icons @angular/cdk
npm i @ngrx/store @ngrx/router-store @ngrx/store-devtools ngrx-store-localstorage @ngrx/effects
npm i @ngrx/eslint-plugin -D
----


=== scripts hinzugefügt

[source,json,source-file="package.json"]
----
  "scripts": {
    "ng": "nx",
    "postinstall": "node ./decorate-angular-cli.js",
    "start": "nx serve bv-admin-app",
    "build:local": "npx nx build bv-admin-app -c local --output-hashing=all --base-href /bv-admin-app/ --skip-nx-cache",
    "build:heikeqs": "npx nx build bv-admin-app -c heikeqs --output-hashing=all --base-href /bv-admin-app/ --skip-nx-cache",
    "build:prod": "npx nx run bv-admin-app:build:production --output-hashing=all --base-href /bv-admin-app/ --skip-nx-cache",
    "test": "npx nx test",
    "test:all": "npx nx run-many --target=test --all",
    "lint:all": "npx nx run-many --target=lint --all",
    "full-check": "npx nx run-s lint:all test:all build",
    "graph": "npx nx graph"
  },

----

=== buildprofile einrichten

Im root-Verzeichnis des workspaces einen Verzeichnisbaum

----
bv-admin-app
  |-- build-env
        |-- environment.heikeqs.ts
        |-- environment.local.ts
        |-- index.heikeqs.html
        |-- index.prod.html
  |-- src
      |-- app
      |-- assets
      |-- environments
  |-- project.json
----

Diese Files werden in project.json verwendet, um die dev-Files zu ersetzen.


=== selector prefix configuriert

Nach prefix suchen und dort app  durch das spezifischere prefix 'auth-admin-app' ergänzen.


=== Sheriff einbinden (erstmal nicht)

Kleines feines https://angular-camp.de/blog/strategic-design-mit-sheriff-und-standalone/[Tutorial]

Sheriff ist ein tool, das ungewünschte direkte dependencies und damit zyklische Abhänigkeiten verhindert.

[source,cli]
----
npm i @softarc/sheriff-core @softarc/eslint-plugin-sheriff -D
----

Anschließend in .eslint.rc einbinden:

[source,json,source-file=".eslint.rc"]
----
{
  [...],
  "overrides": [
    [...]
    {
      "files": ["*.ts"],
      "extends": ["plugin:@softarc/sheriff/default"]
    }
  ]
}
----

Sheriff-Konfigurationsdatei sheriff.config.ts im root-Verzeichnis anlegen und mit der Kopie aus dem Tutorial füllen.

=== Locale konfigurieren in app.config.ts

[src,typescript,source-file="app.config.ts"]
----
import { MAT_DATE_LOCALE } from '@angular/material/core';

...
registerLocaleData(LOCALE_ID, 'de');

...

providers: [
    ...,
    {
      provide: MAT_DATE_LOCALE,
      useValue: 'de-DE',
    },
    { provide: LOCALE_ID, useValue: 'de-DE' },
]
----


== Folders

Ich werde mit einem Konzep aus dem Beispiel https://github.com/softarc-consulting/sheriff/tree/main[angular-iii] entnommen habe. Ohne nx-workspace-Zeug.

Hier werden keine libs generiert, sondern alles nur durch Verzeichnisse strukturiert und über index.ts exportiert. Das scheint mir ein leichtgewichtiger Ansatz für ein neues Projekt zu sein.


=== shared config

Soll einen Provider kapseln, der über environmemt initialisiert wird um environment nirgends anders extra importieren zu müssen.

[src,cli]
----
mkdir src/app/shared/config -p
touch configuration.ts
touch index.ts
----

Eintrag in tsconfig.json

[src,json,source-file="tsconfig.json"]
----
    "paths": {
      "@bv-admin-app/shared/config": ["src/app/shared/config/index.ts"]
    },
----


Dann Configuration in app.config.ts zum Provider machen:

[src,typescript,source-file="app.config.ts"]
----
import { Configuration } from '@bv-admin-app/shared/config';

...
  providers: [
    ...,
    {
      provide: Configuration,
      useFactory: () =>
        new Configuration(
          environment.baseUrl,
          environment.assetsPath,
          'bv-admin-app',
          environment.production
        ),
    },
  ]
----


=== Material-Layout in die shell


[src,cli]
----
mkdir src/app/shell/layout -p
touch index.ts
----

Eintrag in tsconfig.json

[src,json,source-file="tsconfig.json"]
----
    "paths": {
      "@bv-admin-app/shell/layout": ["src/app/shell/layout/index.ts"]
    },
----


Statt

[src,css,source-file="themes.scss"]
----
$mja-primary: mat.define-palette($primary-palette, 700, 300, 900);
----

Muss es jetzt 

[src,css,source-file="themes.scss"]
----
$mja-primary: mat.m2-define-palette($primary-palette, 700, 300, 900);
----

heißen

Dann die styles in project.json eingebunden:


[src,json,source-file="project.json"]
----
...
        "assets": [
          {
            "glob": "**/*",
            "input": "apps/auth-admin-app/src/assets"
          }
        ],
         "styles": [
          "src/app/shell/layout/theme.scss",
          "src/styles.scss",
          "node_modules/material-icons/iconfont/material-icons.scss"
        ],
...
----


==== sidenav

[src,cli]
----
mkdir src/app/shell/layout/sidenav -p
----

Dann die component aus mkbiza-app kopiert und angepasst.

==== navbar

[src,cli]
----
mkdir src/app/shell/layout/navbar -p
----

Dann die component aus mkbiza-app kopiert und angepasst.


=== HomeComponent

[source,cli]
----
npx nx generate @nx/angular:component --name=home --directory=src/app/home --nameAndDirectoryFormat=as-provided --style=scss --no-interactive 
----


