ALTER TABLE authbv.ACCESSTOKENS DROP KEY IF EXISTS uk_accesstokens_1;

ALTER TABLE authbv.ACCESSTOKENS DROP KEY IF EXISTS uk_accesstokens_2;

ALTER TABLE authbv.ACCESSTOKENS DROP FOREIGN KEY IF EXISTS fk_accesstokens_clients;

ALTER TABLE authbv.ACCESSTOKENS DROP KEY IF EXISTS fk_accesstokens_clients;

ALTER TABLE authbv.ACCESSTOKENS ADD UNIQUE KEY uk_cl_accesstokens_1 (`ACCESS_TOKEN`);

ALTER TABLE authbv.ACCESSTOKENS ADD UNIQUE KEY uk_cl_accesstokens_2 (`REFRESH_TOKEN`);

ALTER TABLE authbv.ACCESSTOKENS ADD CONSTRAINT `fk_cl_accesstokens_clients` FOREIGN KEY (`CLIENT_ID`) REFERENCES `CLIENTS` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE authbv.CLIENTS ADD COLUMN `REFRESHTOKEN_EXPIRATION_HOURS` int(4) NOT NULL DEFAULT 6;

ALTER TABLE authbv.CLIENTS ADD COLUMN `ACCESSTOKEN_EXPIRATION_MINUTES` int(4) NOT NULL DEFAULT 17;


CREATE TABLE authbv.USERREFRESHTOKENS (
	`ID` INT UNSIGNED NOT NULL AUTO_INCREMENT,
	`REFRESH_TOKEN` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
    `EXPIRES_AT` datetime NOT NULL,
    `REVOKED` tinyint(1) NOT NULL DEFAULT 0,
    `USER_ID` int(10) unsigned NOT NULL,
    `CLIENT_ID` int(10) unsigned NOT NULL,
	`VERSION` int(10) NOT NULL DEFAULT 0,
	`DATE_MODIFIED` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`ID`),
  UNIQUE KEY `uk_userrefreshtokens_1` (`REFRESH_TOKEN`),
  KEY `fk_userrefreshtokens_users` (`USER_ID`),
  KEY `fk_userrefreshtokens_clients` (`CLIENT_ID`),
  CONSTRAINT `fk_userrefreshtokens_users` FOREIGN KEY (`USER_ID`) REFERENCES `USERS` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `fk_userrefreshtokens_clients` FOREIGN KEY (`CLIENT_ID`) REFERENCES `CLIENTS` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;


