ALTER TABLE authbv.CLIENTS ADD COLUMN `NAMEN_REQUIRED` tinyint(1) NOT NULL DEFAULT '0';
ALTER TABLE authbv.USERS ADD COLUMN `VORNAME` varchar(100) COLLATE utf8_unicode_ci;
ALTER TABLE authbv.USERS ADD COLUMN `NACHNAME` varchar(100) COLLATE utf8_unicode_ci;
