ALTER TABLE authbv.TEMPPWDS DROP COLUMN `REDIRECT_URL`;
ALTER TABLE authbv.TEMPPWDS ADD COLUMN `CLIENT_ID` int(10) unsigned;
ALTER TABLE authbv.TEMPPWDS ADD CONSTRAINT `fk_temppwd_clients` FOREIGN KEY (`CLIENT_ID`) REFERENCES `CLIENTS` (`ID`) ON DELETE CASCADE;

